const syntaxList = [
  { "id": 1, "name": "Python", "extensions": [".py"] },
  { "id": 2, "name": "JavaScript", "extensions": [".js"] },
  { "id": 3, "name": "Java", "extensions": [".java"] },
  { "id": 4, "name": "C++", "extensions": [".cpp", ".cxx", ".cc", ".h", ".hpp"] },
  { "id": 5, "name": "C#", "extensions": [".cs"] },
  { "id": 6, "name": "Ruby", "extensions": [".rb"] },
  { "id": 7, "name": "Swift", "extensions": [".swift"] },
  { "id": 8, "name": "Kotlin", "extensions": [".kt", ".kts"] },
  { "id": 9, "name": "Go", "extensions": [".go"] },
  { "id": 10, "name": "Rust", "extensions": [".rs"] },
  { "id": 11, "name": "PHP", "extensions": [".php"] },
  { "id": 12, "name": "Perl", "extensions": [".pl", ".pm", ".pl6", ".p6", ".t"] },
  { "id": 13, "name": "Haskell", "extensions": [".hs"] },
  { "id": 14, "name": "Lua", "extensions": [".lua"] },
  { "id": 15, "name": "R", "extensions": [".r"] },
  { "id": 16, "name": "Scala", "extensions": [".scala"] },
  { "id": 17, "name": "MATLAB", "extensions": [".m"] },
  { "id": 18, "name": "TypeScript", "extensions": [".ts"] },
  { "id": 19, "name": "Shell Scripting (Bash)", "extensions": [".sh"] },
  { "id": 20, "name": "Objective-C", "extensions": [".m", ".h"] },
  { "id": 21, "name": "Dart", "extensions": [".dart"] },
  { "id": 22, "name": "Julia", "extensions": [".jl"] },
  { "id": 23, "name": "Groovy", "extensions": [".groovy"] },
  { "id": 24, "name": "Racket", "extensions": [".rkt"] },
  { "id": 26, "name": "Erlang", "extensions": [".erl", ".hrl"] },
  { "id": 27, "name": "Crystal", "extensions": [".cr"] },
  { "id": 28, "name": "COBOL", "extensions": [".cob", ".cbl"] },
  { "id": 31, "name": "Scheme", "extensions": [".scm"] },
  { "id": 32, "name": "Prolog", "extensions": [".pl", ".pro"] },
  { "id": 33, "name": "VHDL", "extensions": [".vhd", ".vhdl"] },
  { "id": 34, "name": "Lisp", "extensions": [".lisp", ".lsp"] },
  { "id": 35, "name": "Tcl", "extensions": [".tcl"] },
  { "id": 36, "name": "Elixir", "extensions": [".ex", ".exs"] },
  { "id": 38, "name": "CoffeeScript", "extensions": [".coffee"] },
  { "id": 39, "name": "Clojure", "extensions": [".clj"] },
  { "id": 40, "name": "ActionScript", "extensions": [".as"] },
  { "id": 41, "name": "OCaml", "extensions": [".ml", ".mli"] },
  { "id": 42, "name": "Forth", "extensions": [".4th", ".fth"] },
  { "id": 43, "name": "Assembly (x86)", "extensions": [".asm"] },
  { "id": 45, "name": "SQL", "extensions": [".sql"] },
  { "id": 49, "name": "Fortran", "extensions": [".f", ".for", ".f77", ".f90", ".f95"] },
  { "id": 50, "name": "RPG", "extensions": [".rpg", ".rpgle"] },
  { "id": 56, "name": "HTML", "extensions": [".html", ".htm"] },
  { "id": 57, "name": "CSS", "extensions": [".css"] },
  { "id": 58, "name": "XML", "extensions": [".xml"] },
  { "id": 59, "name": "JSON", "extensions": [".json"] },
  { "id": 60, "name": "YAML", "extensions": [".yaml", ".yml"] },
  { "id": 61, "name": "Markdown", "extensions": [".md", ".markdown"] },
  { "id": 62, "name": "TeX", "extensions": [".tex"] },
  { "id": 63, "name": "LaTeX", "extensions": [".latex"] },
  { "id": 66, "name": "NoSQL", "extensions": [".json", ".xml"] },
  { "id": 68, "name": "Pascal", "extensions": [".pas"] },
  { "id": 71, "name": "F#", "extensions": [".fs", ".fsi", ".fsx", ".fsscript"] },
  { "id": 80, "name": "Ada", "extensions": [".ada", ".adb", ".ads"] },
]

export default syntaxList
