jwt:
  key: Y1pcIlSppsWJSNeYNTNTvqk2EI0H4q1jlQyZ8jFNaXCkR50lgK4b9f0LN3iHrgtm
spring:
  datasource:
    url: jdbc:postgresql://ep-divine-star-78931188.eu-central-1.aws.neon.tech/neondb
    username: akinwale-habibullah
    password: fO9LCzcbTBA7
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
