spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pastebin
    username: akinwalehabib
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
